CREATE TABLE tb_user (
	uid INTEGER NOT NULL PRIMARY KEY,
	usertype INTEGER NOT NULL DEFAULT 0,
	lastip CHAR(15) NOT NULL DEFAULT '',
	lasttime INTEGER NOT NULL DEFAULT 0,
	score INTEGER NOT NULL DEFAULT 0,
	points INTEGER NOT NULL DEFAULT 0,
	charged INTEGER NOT NULL DEFAULT 0,
	KEY (lasttime),
	KEY (score));

CREATE TABLE tb_retry (
	username CHAR(15) NOT NULL PRIMARY KEY,
	retrycount INTEGER NOT NULL DEFAULT 0,
	retrytime INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_password (
	username CHAR(15) NOT NULL PRIMARY KEY,
	email CHAR(32) NOT NULL,
	password CHAR(6) NOT NULL,
	eventip CHAR(15) NOT NULL,
	eventtime INTEGER NOT NULL);

CREATE TABLE tb_rankw (
	uid INTEGER NOT NULL PRIMARY KEY,
	score INTEGER NOT NULL DEFAULT 0,
	rank INTEGER NOT NULL AUTO_INCREMENT,
	KEY (rank));

CREATE TABLE tb_rankw0 (
	uid INTEGER NOT NULL PRIMARY KEY,
	rank INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_rankm (
	uid INTEGER NOT NULL PRIMARY KEY,
	score INTEGER NOT NULL DEFAULT 0,
	rank INTEGER NOT NULL AUTO_INCREMENT,
	KEY (rank));

CREATE TABLE tb_rankm0 (
	uid INTEGER NOT NULL PRIMARY KEY,
	rank INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_rankq (
	uid INTEGER NOT NULL PRIMARY KEY,
	score INTEGER NOT NULL DEFAULT 0,
	rank INTEGER NOT NULL AUTO_INCREMENT,
	KEY (rank));

CREATE TABLE tb_rankq0 (
	uid INTEGER NOT NULL PRIMARY KEY,
	rank INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_chargecode (
	chargecode CHAR(32) NOT NULL PRIMARY KEY,
	points INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_log (
	uid INTEGER NOT NULL,
	eventip VARCHAR(16) NOT NULL,
	eventtime INTEGER NOT NULL,
	eventtype INTEGER NOT NULL,
	detail INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_task (
	taskname VARCHAR(64) NOT NULL PRIMARY KEY,
	lasttime INTEGER NOT NULL DEFAULT 0,
	nexttime INTEGER NOT NULL DEFAULT 0,
	tasklock INTEGER NOT NULL DEFAULT 0);

INSERT INTO tb_task (taskname) VALUES ("dailytask");

CREATE TABLE tb_questionnaire (
	eventip CHAR(15) NOT NULL,
	eventtime INTEGER NOT NULL,
	a1 TINYINT NOT NULL,
	a2 TINYINT NOT NULL,
	a3 TINYINT NOT NULL,
	a4 TINYINT NOT NULL,
	a5 TINYINT NOT NULL,
	a6 TINYINT NOT NULL,
	a7 TINYINT NOT NULL,
	a8 TINYINT NOT NULL,
	a9 TINYINT NOT NULL,
	a10 TINYINT NOT NULL,
	a11 TINYINT NOT NULL,
	a12 TINYINT NOT NULL,
	a13 TINYINT NOT NULL,
	a14 TINYINT NOT NULL,
	a15 TINYINT NOT NULL,
	a16 TINYINT NOT NULL,
	a17 TINYINT NOT NULL,
	a18 TINYINT NOT NULL,
	a19 TINYINT NOT NULL,
	a20 TINYINT NOT NULL,
	comments VARCHAR(255) NOT NULL);