CREATE TABLE tb_user (
	username VARCHAR(64) NOT NULL PRIMARY KEY,
	usertype INTEGER NOT NULL DEFAULT 0,
	password CHAR(32) NOT NULL,
	email VARCHAR(64) NOT NULL, 
	regip VARCHAR(16) NOT NULL,
	regtime INTEGER NOT NULL,
	lastip VARCHAR(16) NOT NULL DEFAULT "",
	lasttime INTEGER NOT NULL DEFAULT 0,
	retrycount INTEGER NOT NULL DEFAULT 0,
	retrytime INTEGER NOT NULL DEFAULT 0,
	scores INTEGER NOT NULL DEFAULT 0,
	points INTEGER NOT NULL DEFAULT 0);

CREATE TABLE tb_log (
	username VARCHAR(64) NOT NULL,
	eventip VARCHAR(16) NOT NULL,
	eventtime INTEGER NOT NULL,
	eventtype INTEGER NOT NULL,
	detail INTEGER NOT NULL DEFAULT 0);