CREATE TABLE tb_login (
	cookie CHAR(32) NOT NULL PRIMARY KEY,
	uid INTEGER NOT NULL,
	expire INTEGER NOT NULL,
	KEY (expire));

CREATE TABLE tb_pgn (
	sid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	year INTEGER NOT NULL,
	month INTEGER NOT NULL,
	event VARCHAR(256) NOT NULL,
	round CHAR(16) NOT NULL,
	date CHAR(16) NOT NULL,
	site CHAR(16) NOT NULL,
	redteam CHAR(16) NOT NULL,
	red CHAR(16) NOT NULL,
	blackteam CHAR(16) NOT NULL,
	black CHAR(16) NOT NULL,
	movelist TEXT NOT NULL,
	ecco INTEGER NOT NULL,
	maxmoves INTEGER NOT NULL,
	result INTEGER NOT NULL,
	KEY (ecco));