CREATE TABLE xq_user (
	uid INTEGER NOT NULL PRIMARY KEY,
	usertype INTEGER NOT NULL DEFAULT 0,
	lastip CHAR(15) NOT NULL DEFAULT '',
	lasttime INTEGER NOT NULL DEFAULT 0,
	score INTEGER NOT NULL DEFAULT 0,
	points INTEGER NOT NULL DEFAULT 0,
	charged INTEGER NOT NULL DEFAULT 0,
	upload INTEGER NOT NULL DEFAULT 0,
	download INTEGER NOT NULL DEFAULT 0,
	balance INTEGER NOT NULL DEFAULT 0,
	income INTEGER NOT NULL DEFAULT 0,
	KEY (upload),
	KEY (download));

CREATE TABLE xq_login (
	cookie CHAR(32) NOT NULL PRIMARY KEY,
	uid INTEGER NOT NULL,
	expire INTEGER NOT NULL,
	KEY (expire));

CREATE TABLE xq_retry (
	uid INTEGER NOT NULL PRIMARY KEY,
	retrycount INTEGER NOT NULL DEFAULT 0,
	retrytime INTEGER NOT NULL DEFAULT 0);

CREATE TABLE xq_rank (
	uid INTEGER NOT NULL PRIMARY KEY,
	score INTEGER NOT NULL DEFAULT 0,
	rank INTEGER NOT NULL AUTO_INCREMENT,
	KEY (rank));

CREATE TABLE xq_rank0 (
	uid INTEGER NOT NULL PRIMARY KEY,
	rank INTEGER NOT NULL DEFAULT 0);

CREATE TABLE xq_chargecode (
	chargecode CHAR(32) NOT NULL PRIMARY KEY,
	points INTEGER NOT NULL DEFAULT 0);

CREATE TABLE xq_log (
	uid INTEGER NOT NULL,
	eventip VARCHAR(16) NOT NULL,
	eventtime INTEGER NOT NULL,
	eventtype INTEGER NOT NULL,
	detail INTEGER NOT NULL DEFAULT 0);

CREATE TABLE xq_qn_user (
	uid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	eventip CHAR(15) NOT NULL,
	eventtime INTEGER NOT NULL);

CREATE TABLE xq_qn_answer (
	uid INTEGER NOT NULL,
	qid INTEGER NOT NULL,
	answer INTEGER NOT NULL);

CREATE TABLE xq_qn_comment (
	uid INTEGER NOT NULL,
	comment VARCHAR(255) NOT NULL);

CREATE TABLE xq_upload (
	fid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	uid INTEGER NOT NULL,
	filename CHAR(32) NOT NULL,
	savename CHAR(32) NOT NULL,
	title CHAR(32) NOT NULL,
	catagory INTEGER NOT NULL,
	size INTEGER NOT NULL,
	price INTEGER NOT NULL,
	eventtime INTEGER NOT NULL,
	download INTEGER NOT NULL DEFAULT 0,
	positive INTEGER NOT NULL DEFAULT 0,
	negative INTEGER NOT NULL DEFAULT 0,
	state INTEGER NOT NULL DEFAULT 0,
	KEY (uid),
	KEY (eventtime),
	KEY (download),
	KEY (positive));

CREATE TABLE xq_download (
	fid INTEGER NOT NULL,
	uid INTEGER NOT NULL,
	grade INTEGER NOT NULL,
	PRIMARY KEY (fid, uid),
	KEY (uid));

CREATE TABLE xq_download_comment (
	fid INTEGER NOT NULL,
	uid INTEGER NOT NULL,
	comment VARCHAR(255) NOT NULL,
	eventtime INTEGER NOT NULL,
	PRIMARY KEY (fid, uid));

CREATE TABLE xq_pgn (
	sid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	year INTEGER NOT NULL,
	month INTEGER NOT NULL,
	event VARCHAR(256) NOT NULL,
	round CHAR(16) NOT NULL,
	date CHAR(16) NOT NULL,
	site CHAR(16) NOT NULL,
	redteam CHAR(16) NOT NULL,
	red CHAR(16) NOT NULL,
	blackteam CHAR(16) NOT NULL,
	black CHAR(16) NOT NULL,
	movelist TEXT NOT NULL,
	ecco INTEGER NOT NULL,
	maxmoves INTEGER NOT NULL,
	result INTEGER NOT NULL,
	KEY (ecco));